# -*- coding: utf-8 -*-
"""testcolor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nockSYLcz9g91ZPTmv_gXz1FxqWQIU5v
"""

import os
import sys

class testcolor:

  def __init__(self):
    os.system('git clone https://github.com/ImagingLab/Colorizing-with-GANs.git')
    os.system('cd Colorizing-with-GANs')
    os.system('pip install -r requirements.txt')

  def train(self):
    os.system('python train.py \
      --seed 100 \
      --dataset clean \
      --dataset-path ./content/Train/clean \
      --checkpoints-path ./checkpoints \
      --batch-size 16 \
      --epochs 10 \
      --lr 3e-4 \
      --label-smoothing 1')







